export { WatchGood } from "../components/AddWishList/AddWishList";
export { WishList } from "../components/AddWishList/AddWishList";
export { default as CartColor } from "../components/Cart/cartColor/CartColor";
export { default as CartTodays } from "../components/Cart/CartTodays/CartTodays";
export { default as ProductCart } from "../components/Cart/ProductCart/ProductCart";
export { default as OneCart } from "../components/Cart/CartTodays/oneCart/OneCart";
export { default as InfoBar } from "../components/InfoBar/InfoBar";
export { InputGray, InputWhite } from "../components/Input/input";
export { default as Catalog } from "../components/Regular/catalog/Catalog";
export { default as Filter } from "../components/Regular/catalog/filter/Filter";
export { default as MenuMobile } from "../components/Regular/MenuMobile/MenuMobile";
export { default as Price } from "../components/Regular/price/Price";
export { default as Product } from "../components/Regular/productInfo/product/Product";
export { default as ProductDetail } from "../components/Regular/productDetail/ProductDetail";
export { default as ProductsInfo } from "../components/Regular/productInfo/ProductsInfo";
export { default as Banner } from "../components/UI/Banner/Banner";
export { default as BannerProduct } from "../components/UI/Banner/bannerProduct/BannerProduct";
export { default as Button } from "../components/UI/Button/Button";
export { default as Loader } from "../components/UI/loader/Loader";
export { default as Pagination } from "../components/UI/pagination/Pagination";
export { default as RangeSlider } from "../components/UI/rangeSlider/RangeSlider";
export { default as Slider } from "../components/UI/slider/Slider";
export { SliderColor } from "../components/UI/slider/Slider";
export { default as DealsInformation } from "../components/Regular/DealsIformation/DealsInformation";
export { default as Reviews } from "../components/Regular/Reviews/Reviews";
export { default as Sort } from "../components/UI/sort/Sort";
export { default as Cart } from "../components/Cart/Cart/Cart";
