// export { default as CartColor } from "../components/Cart/CartColor/CartColor";
export { default as CartTodays } from "../components/Cart/CartTodays/CartTodays";
export { default as ProductCart } from "../components/Cart/ProductCart/ProductCart";
// export { default as OneCart } from "../components/Cart/CartTodays/OneCart/OneCart";
export { default as InfoBar } from "../components/Regular/InfoBar/InfoBar";
export { default as Search } from "../components/Ui/Search/Search";
export { default as Catalog } from "../components/Regular/catalog/Catalog";
// export { default as Filter } from "../components/Regular/catalog/Filter/Filter";
export { default as MenuMobile } from "../components/Regular/MenuMobile/MenuMobile";
export { default as Price } from "../components/Regular/price/Price";
export { default as Product } from "../components/Regular/productInfo/Product";
export { default as ProductDetail } from "../components/Regular/productDetail/ProductDetail";
export { default as BannerProducts } from "../components/Ui/BannerProducts/BannerProducts";
export { default as Banner } from "../components/Ui/Banner/Banner";
export { default as Button } from "../components/Ui/Button/Button";
export { default as Loader } from "../components/Ui/loader/Loader";
export { default as Pagination } from "../components/Ui/pagination/Pagination";
export { default as RangeSlider } from "../components/Ui/rangeSlider/RangeSlider";
// export { default as Slider } from "../components/UI/Slider/Slider";
export { default as ProductColorSlider } from "../components/Ui/ProductColorSlider/ProductColorSlider";
export { default as ProductEmpty } from "../components/Regular/ProductEmpty/ProductEmpty";
export { default as Reviews } from "../components/Regular/Reviews/Reviews";
// export { default as Sort } from "../components/UI/Sort/Sort";
export { default as Cart } from "../components/Cart/Cart";
export { default as IconMenu } from "../components/Regular/IconMenu/IconMenu";
export { default as GrayLine } from "../components/Ui/GrayLine/GrayLine";
export { default as DeliveryAddress } from "../components/Ui/UserDate/DeliveryAddress/DeliveryAddress";
export { default as UserAllDate } from "../components/Ui/UserDate/UserAllDate/UserAllDate";
export { default as ButtonScroll } from "../components/Ui/ButtonScroll/ButtonScroll";
export { default as ResetPassword } from "../components/Regular/ResetPassword/ResetPassword";
export { default as CartContentName } from "../components/Regular/CartContentName/CartContentName";
export { default as Coupon } from "../components/Ui/Coupon/Coupon";
export { default as Qunatity } from "../components/Ui/Quantity/Quantity";
export { default as CartEmpty } from "../components/Ui/CartEmpty/CartEmpty";
export { default as Input } from "../components/Ui/input/Input";
export { default as WatchProduct } from "../components/Regular/WatchProduct/WatchProduct";
export { default as InfoBarUser } from "../components/Regular/InfoUserBar/InfoUserBar";
export { default as InfoUserDetails } from "../components/Regular/InfoUserDetail/InfoUserDetails";
