// export { default as CartColor } from "../components/Cart/CartColor/CartColor";
export { default as CartTodays } from "../components/Cart/CartTodays/CartTodays";
export { default as ProductCart } from "../components/Cart/ProductCart/ProductCart";
// export { default as OneCart } from "../components/Cart/CartTodays/OneCart/OneCart";
export { default as InfoBar } from "../components/InfoBar/InfoBar";
export { default as Search } from "../components/Search/Search";
export { default as Catalog } from "../components/catalog/Catalog";
// export { default as Filter } from "../components/Regular/catalog/Filter/Filter";
export { default as MenuMobile } from "../components/MenuMobile/MenuMobile";
export { default as Price } from "../components/price/Price";
export { default as Product } from "../components/productInfo/Product";
export { default as ProductDetail } from "../components/productDetail/ProductDetail";
export { default as BannerProducts } from "../components/BannerProducts/BannerProducts";
export { default as Banner } from "../components/Banner/Banner";
export { default as Button } from "../components/Button/Button";
export { default as Loader } from "../components/loader/Loader";
export { default as Pagination } from "../components/pagination/Pagination";
export { default as RangeSlider } from "../components/rangeSlider/RangeSlider";
// export { default as Slider } from "../components/UI/Slider/Slider";
export { default as ProductColorSlider } from "../components/ProductColorSlider/ProductColorSlider";
export { default as ProductEmpty } from "../components/ProductEmpty/ProductEmpty";
export { default as Reviews } from "../components/Reviews/Reviews";
// export { default as Sort } from "../components/UI/Sort/Sort";
export { default as Cart } from "../components/Cart/Cart";
export { default as IconMenu } from "../components/IconMenu/IconMenu";
export { default as GrayLine } from "../components/GrayLine/GrayLine";
export { default as DeliveryAddress } from "../components/UserDate/DeliveryAddress/DeliveryAddress";
export { default as UserAllDate } from "../components/UserDate/UserAllDate/UserAllDate";
export { default as ButtonScroll } from "../components/ButtonScroll/ButtonScroll";
export { default as ResetPassword } from "../components/ResetPassword/ResetPassword";
export { default as CartContentName } from "../components/CartContentName/CartContentName";
export { default as Coupon } from "../components/Coupon/Coupon";
export { default as Qunatity } from "../components/Quantity/Quantity";
export { default as CartEmpty } from "../components/CartEmpty/CartEmpty";
export { default as Input } from "../components/input/Input";
export { default as WatchProduct } from "../components/WatchProduct/WatchProduct";
export { default as InfoBarUser } from "../components/InfoUserBar/InfoUserBar";
export { default as InfoUserDetails } from "../components/InfoUserDetail/InfoUserDetails";
